version: '3.8'

services:
  slack-bot:
    build: .
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./data:/app/data
